language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

sudo: false

bundler_args: "--without docs"

# before_script:

script:
  - bundle install --without docs
  - bundle exec make test

notifications:
  email:
    - vasusen@wepay.com
